---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://helm.traefik.io/traefik

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
      version: 10.24.2
  interval: 1m0s
  releaseName: traefik
  targetNamespace: default

---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: traefik-crds
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/traefik/traefik-helm-chart.git
  ref:
    tag: v10.3.0
  ignore: |
    # exclude all
    /*
    # path to crds
    !/traefik/crds/

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: traefik-api-crds
  namespace: flux-system
spec:
  interval: 15m
  prune: false
  sourceRef:
    kind: GitRepository
    name: traefik-crds
    namespace: flux-system

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: frontend-ingress-route-secure
  namespace: default
spec:
  tls:
    certResolvers:
      myresolver:
        email: "nettemsarath1@gmail.com"
        storage: "/data/acme.json"
        dnsChallenge:
          # used during the challenge
          provider: godaddy

      env:
        - name: GODADDY_API_KEY
          value: "3mM44UcgfH6Kbp_VUpWjcVY6DedYbqbv1Qqdu"
        - name: GODADDY_API_SECRET
          value: "G5KrhmfU8WscMbHrBwisAg"
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`test.nettemsarath.com`) || Path(`/`) || PathPrefix(`/`)
      kind: Rule
      services:
        - name: hello-app-demo
          port: 80
# # helm install --namespace traefik --values=./cert-issuer.yml traefik traefik/traefik
# # helm install traefik traefik/traefik --configFile=cert-issuer.yml

# #  traefik --configFile=foo/bar/myconfigfile.yml

# certResolvers:
#   myresolver:
#     email: "nettemsarath1@gmail.com"
#     storage: "/data/acme.json"
#     dnsChallenge:
#       # used during the challenge
#       provider: godaddy

#   env:
#     - name: GODADDY_API_KEY
#       value: "3mM44UcgfH6Kbp_VUpWjcVY6DedYbqbv1Qqdu"
#     - name: GODADDY_API_SECRET
#       value: "G5KrhmfU8WscMbHrBwisAg"
