apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 30m
  url: https://traefik.github.io/charts
# https://traefik.github.io/charts
