---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: podsource
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/nettemsarath/fleet-infra
