---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-router
  namespace: default
spec:
  # tls:
  #   certResolver: myresolver
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`test.nettemsarath.com`) || Path(`/`) || PathPrefix(`/`)
      kind: Rule
      services:
        - name: hello-app-demo
          port: 80
